version: "3.7"
services:
  api:
    build: .
    command: bash -c | "sh ./scripts/archive_model.sh && 
                        sh ./scripts/start_torchserve.sh"
    volumes:
        - ./models/:/models
        - ./model-store:/model-store
    ports:
      - "8080:8080"